apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyage-analytics-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voyage-analytics
  template:
    metadata:
      labels:
        app: voyage-analytics
    spec:
      containers:
      - name: voyage-analytics-container
        image: voyage-analytics-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
