apiVersion: v1
kind: Service
metadata:
  name: voyage-analytics-service
spec:
  type: NodePort
  selector:
    app: voyage-analytics
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
